/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BAccordion: typeof import('bootstrap-vue-next')['BAccordion']
    BAccordionItem: typeof import('bootstrap-vue-next')['BAccordionItem']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BInputGroupAppend: typeof import('bootstrap-vue-next')['BInputGroupAppend']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue-next')['BNavForm']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BPagination: typeof import('bootstrap-vue-next')['BPagination']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    BTableLite: typeof import('bootstrap-vue-next')['BTableLite']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTfoot: typeof import('bootstrap-vue-next')['BTfoot']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BThead: typeof import('bootstrap-vue-next')['BThead']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    copy: typeof import('./src/components/temp copy.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Temp: typeof import('./src/components/temp.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    Write: typeof import('./src/components/write.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next')['vBColorMode']
  }
}
